VFS-13189 Update bamboo specs to enable execution of only selected tests

diff --git a/bamboo-specs/gui-acceptance-pkg.yml b/bamboo-specs/gui-acceptance-pkg.yml
--- a/bamboo-specs/gui-acceptance-pkg.yml
+++ b/bamboo-specs/gui-acceptance-pkg.yml
@@ -60,11 +60,13 @@ stages:
       manual: false
       final: false
       jobs:
-        # - _Codetag Tracker
-        # - _Autoformatter check
-        # - _Static analysis
-        # - _Type_check
-        # - Atm examples workflows 1
+        - _Codetag Tracker
+        - _Autoformatter check
+        - _Static analysis
+        - _Type_check
+        - Atm examples workflows 1
+        - Storage sync
+        - Storage sync charts
         # - Atm examples workflows 2
         # - Atm pods
         # - Atm stores basic
@@ -148,8 +150,6 @@ stages:
         # - QoS storage
         # - Shares basic
         # - Shares handle service
-        - Storage sync
-        - Storage sync charts
         # - Transfers cancel
         # - Transfers directories
         # - Transfers files
@@ -288,125 +288,125 @@ _Type_check:
           - make type-check
         description: Type checker
 
-# Atm examples workflows 1: &acceptance-tests-in-chrome-job
-#   key: COAWEX2
-#   other: *common-opts
-#   tasks:
-#     - script: &clear-env
-#         <<: *run-script
-#         scripts:
-#           - curl ${bamboo.OnedataFinalTasksURL} | bash -
-#         description: Clear env
-#     - script: &restart-minikube
-#         <<: *run-script
-#         scripts:
-#           - sudo ${HOME}/restart_minikube.sh
-#         description: Restart minikube
-#     - checkout: *checkout-default-repository
-#     - script: &init-submodules
-#         <<: *run-script
-#         conditions:
-#           - variable:
-#               matches:
-#                 bamboo.buildNumber: '[2-9]|.{2,}'
-#     - script: &quarantine-hack-pull-surefire
-#         <<: *run-script-working-dir
-#         scripts:
-#           - |-
-#             #!/bin/bash
-#             ARTIFACT="surefire_${bamboo_shortJobName// /_}.tar.gz"
-#             echo ./bamboos/artifacts/pull_artifact.py --hostname ${bamboo.artifactRepoHostname} --port ${bamboo.artifactRepoPort} \
-#                 --username ${bamboo.artifactRepoUsername} --branch ${bamboo.quarantineSourceBranch} --plan ${bamboo.planRepository.name} \
-#                 --artifact-name ${ARTIFACT}
-#             let c=3
-#             while : ; do
-#                 ./bamboos/artifacts/pull_artifact.py --hostname ${bamboo.artifactRepoHostname} --port ${bamboo.artifactRepoPort} \
-#                     --username ${bamboo.artifactRepoUsername} --branch ${bamboo.quarantineSourceBranch} --plan ${bamboo.planRepository.name} \
-#                     --artifact-name ${ARTIFACT}
-#                 tar zxf ${ARTIFACT}
-#                 if [ -f test-reports/results*.xml ]; then
-#                     break
-#                 else
-#                     let c=$c-1
-#                     if [[ $c < 0 ]]; then
-#                         echo "Giving up... The surefire file 'results.xml' could not be pulled. Does it exist in the develop?" >&2
-#                         break
-#                     fi
-#                     echo "The surefire file 'results.xml' could not be pulled, retrying in 30 seconds..." >&2
-#                     sleep 30
-#                 fi
-#             done
-#             touch test-reports/results*.xml
-#         description: Pull surefire artifact and unpack it
-#         conditions:
-#           - variable:
-#               matches:
-#                 bamboo.buildNumber: '2|3'
-#     - script: &download-artifacts
-#         <<: *run-script-working-dir
-#         scripts:
-#           - |-
-#             echo one-env/onenv pull_artifacts --hostname ${bamboo.artifactRepoHostname} --port ${bamboo.artifactRepoPort} --packages-only branchConfig.yaml
-#             one-env/onenv pull_artifacts --hostname ${bamboo.artifactRepoHostname} --port ${bamboo.artifactRepoPort} --packages-only branchConfig.yaml
-#         description: Download artifacts
-#     - script: &run-selenium-tests
-#         <<: *run-script-working-dir
-#         scripts:
-#           - make ENV_FILE=1oz_1op_openfaas SUITE=test_automation_examples_workflows_tests1 test_gui_pkg
-#         description: Run Selenium tests
-#   final-tasks:
-#     - test-parser:
-#         type: junit
-#         ignore-time: "false"
-#         test-results: onedata-acceptance/test-reports/results*.xml
-#         description: Parse test results
-#     - script:
-#         <<: *run-script-working-dir
-#         scripts:
-#           - |-
-#             #!/bin/bash
-#             ARTIFACT=surefire_${bamboo_shortJobName// /_}.tar.gz
-#             tar czf ${ARTIFACT} test-reports/results*.xml
-#             echo ./bamboos/artifacts/push_artifact.py --hostname ${bamboo.artifactRepoHostname} --port ${bamboo.artifactRepoPort} \
-#                 --username ${bamboo.artifactRepoUsername} --branch ${bamboo.planRepository.branchName} --plan ${bamboo.planRepository.name} \
-#                 --artifact-name ${ARTIFACT}
-#             ./bamboos/artifacts/push_artifact.py --hostname ${bamboo.artifactRepoHostname} --port ${bamboo.artifactRepoPort} \
-#                 --username ${bamboo.artifactRepoUsername} --branch ${bamboo.planRepository.branchName} --plan ${bamboo.planRepository.name} \
-#                 --artifact-name ${ARTIFACT}
-#         description: Pack and push surefire artifact
-#     - script:
-#         <<: *run-script
-#         scripts:
-#           - |-
-#             cp onedata-acceptance/test-reports/*.xml onedata-acceptance/tests/gui/logs
-#             cp onedata-acceptance/one-env/sources_info.yaml onedata-acceptance/tests/gui/logs
-#             mv onedata-acceptance/tests/gui/logs/report.* onedata-acceptance/tests/gui/logs/gui_report
-#             mv onedata-acceptance/tests/gui/logs/gui_report/images.yaml onedata-acceptance/tests/gui/logs
-#         description: Pack logs
-#     - script:
-#         <<: *run-script-working-dir
-#         scripts:
-#           - curl ${bamboo.OnedataFinalTasksURL} | bash -
-#         description: Clear env and working dir
-#     - script:
-#         scripts:
-#           - |-
-#             echo "No real testing done on build 2 - only unpacking of surefire artifact (see above logs). The job is forced to fail."
-#             false
-#         conditions:
-#           - variable:
-#               matches:
-#                 bamboo.buildNumber: '2'
-#         description: Qnthack - always fail on build 2
-#   artifacts:
-#     - name: report
-#       location: onedata-acceptance/tests/gui/logs/
-#       pattern: "**/*.*"
-#       shared: false
-#       required: false
-#   requirements:
-#     - minikube
-#   artifact-subscriptions: [ ]
+Atm examples workflows 1: &acceptance-tests-in-chrome-job
+  key: COAWEX2
+  other: *common-opts
+  tasks:
+    - script: &clear-env
+        <<: *run-script
+        scripts:
+          - curl ${bamboo.OnedataFinalTasksURL} | bash -
+        description: Clear env
+    - script: &restart-minikube
+        <<: *run-script
+        scripts:
+          - sudo ${HOME}/restart_minikube.sh
+        description: Restart minikube
+    - checkout: *checkout-default-repository
+    - script: &init-submodules
+        <<: *run-script
+        conditions:
+          - variable:
+              matches:
+                bamboo.buildNumber: '[2-9]|.{2,}'
+    - script: &quarantine-hack-pull-surefire
+        <<: *run-script-working-dir
+        scripts:
+          - |-
+            #!/bin/bash
+            ARTIFACT="surefire_${bamboo_shortJobName// /_}.tar.gz"
+            echo ./bamboos/artifacts/pull_artifact.py --hostname ${bamboo.artifactRepoHostname} --port ${bamboo.artifactRepoPort} \
+                --username ${bamboo.artifactRepoUsername} --branch ${bamboo.quarantineSourceBranch} --plan ${bamboo.planRepository.name} \
+                --artifact-name ${ARTIFACT}
+            let c=3
+            while : ; do
+                ./bamboos/artifacts/pull_artifact.py --hostname ${bamboo.artifactRepoHostname} --port ${bamboo.artifactRepoPort} \
+                    --username ${bamboo.artifactRepoUsername} --branch ${bamboo.quarantineSourceBranch} --plan ${bamboo.planRepository.name} \
+                    --artifact-name ${ARTIFACT}
+                tar zxf ${ARTIFACT}
+                if [ -f test-reports/results*.xml ]; then
+                    break
+                else
+                    let c=$c-1
+                    if [[ $c < 0 ]]; then
+                        echo "Giving up... The surefire file 'results.xml' could not be pulled. Does it exist in the develop?" >&2
+                        break
+                    fi
+                    echo "The surefire file 'results.xml' could not be pulled, retrying in 30 seconds..." >&2
+                    sleep 30
+                fi
+            done
+            touch test-reports/results*.xml
+        description: Pull surefire artifact and unpack it
+        conditions:
+          - variable:
+              matches:
+                bamboo.buildNumber: '2|3'
+    - script: &download-artifacts
+        <<: *run-script-working-dir
+        scripts:
+          - |-
+            echo one-env/onenv pull_artifacts --hostname ${bamboo.artifactRepoHostname} --port ${bamboo.artifactRepoPort} --packages-only branchConfig.yaml
+            one-env/onenv pull_artifacts --hostname ${bamboo.artifactRepoHostname} --port ${bamboo.artifactRepoPort} --packages-only branchConfig.yaml
+        description: Download artifacts
+    - script: &run-selenium-tests
+        <<: *run-script-working-dir
+        scripts:
+          - make ENV_FILE=1oz_1op_openfaas SUITE=test_automation_examples_workflows_tests1 test_gui_pkg
+        description: Run Selenium tests
+  final-tasks:
+    - test-parser:
+        type: junit
+        ignore-time: "false"
+        test-results: onedata-acceptance/test-reports/results*.xml
+        description: Parse test results
+    - script:
+        <<: *run-script-working-dir
+        scripts:
+          - |-
+            #!/bin/bash
+            ARTIFACT=surefire_${bamboo_shortJobName// /_}.tar.gz
+            tar czf ${ARTIFACT} test-reports/results*.xml
+            echo ./bamboos/artifacts/push_artifact.py --hostname ${bamboo.artifactRepoHostname} --port ${bamboo.artifactRepoPort} \
+                --username ${bamboo.artifactRepoUsername} --branch ${bamboo.planRepository.branchName} --plan ${bamboo.planRepository.name} \
+                --artifact-name ${ARTIFACT}
+            ./bamboos/artifacts/push_artifact.py --hostname ${bamboo.artifactRepoHostname} --port ${bamboo.artifactRepoPort} \
+                --username ${bamboo.artifactRepoUsername} --branch ${bamboo.planRepository.branchName} --plan ${bamboo.planRepository.name} \
+                --artifact-name ${ARTIFACT}
+        description: Pack and push surefire artifact
+    - script:
+        <<: *run-script
+        scripts:
+          - |-
+            cp onedata-acceptance/test-reports/*.xml onedata-acceptance/tests/gui/logs
+            cp onedata-acceptance/one-env/sources_info.yaml onedata-acceptance/tests/gui/logs
+            mv onedata-acceptance/tests/gui/logs/report.* onedata-acceptance/tests/gui/logs/gui_report
+            mv onedata-acceptance/tests/gui/logs/gui_report/images.yaml onedata-acceptance/tests/gui/logs
+        description: Pack logs
+    - script:
+        <<: *run-script-working-dir
+        scripts:
+          - curl ${bamboo.OnedataFinalTasksURL} | bash -
+        description: Clear env and working dir
+    - script:
+        scripts:
+          - |-
+            echo "No real testing done on build 2 - only unpacking of surefire artifact (see above logs). The job is forced to fail."
+            false
+        conditions:
+          - variable:
+              matches:
+                bamboo.buildNumber: '2'
+        description: Qnthack - always fail on build 2
+  artifacts:
+    - name: report
+      location: onedata-acceptance/tests/gui/logs/
+      pattern: "**/*.*"
+      shared: false
+      required: false
+  requirements:
+    - minikube
+  artifact-subscriptions: [ ]
 
 # Atm examples workflows 2:
 #   <<: *acceptance-tests-in-chrome-job
